=== bear-metal-apps/beariscope/lib/assets/schema/data_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Beariscope Data Schema",
  "type": "object",
  "properties": {
    "metadata": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/dataField"
      }
    },
    "auto": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/dataField"
      }
    },
    "tele": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/dataField"
      }
    },
    "endgame": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/dataField"
      }
    }
  },
  "required": [
    "metadata",
    "auto",
    "tele",
    "endgame"
  ],
  "$defs": {
    "dataField": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "display_name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "integer",
            "string",
            "boolean"
          ]
        },
        "enum": {
          "type": "array",
          "items": {}
        }
      },
      "required": [
        "id",
        "display_name",
        "type"
      ]
    }
  }
}

=== bear-metal-apps/beariscope/lib/assets/schema/2025/strat.json
{
  "$schema": "/lib/assets/schema/data_schema.json",
  "metadata": [
    {
      "id": "match_number",
      "display_name": "Match Number",
      "type": "integer"
    },
    {
      "id": "event_key",
      "display_name": "Event Key",
      "type": "string"
    },
    {
      "id": "is_red_alliance",
      "display_name": "Red Alliance",
      "type": "boolean"
    },
    {
      "id": "human_net_scored",
      "display_name": "Human Scored",
      "type": "integer"
    },
    {
      "id": "human_net_missed",
      "display_name": "Human Missed",
      "type": "integer"
    }
  ],
  "auto": [
  ],
  "tele": [
  ],
  "endgame": [
  ]
}

=== bear-metal-apps/beariscope/lib/assets/schema/2025/UIs/2025-1.json
{
  "$schema": "/lib/assets/schema/UI_schema.json",
  "metadata": [
    {
      "id": "button_opacity",
      "display_name": "Button Opacity",
      "type": "integer"
    },
    {
      "id": "text_font",
      "display_name": "Font",
      "type": "string"
    },
    {
      "id": "grid_x",
      "display_name": "X Vertex Count",
      "type": "integer"
    },
    {
      "id": "grid_y",
      "display_name": "Y Vertex Count",
      "type": "integer"
    },
    {
      "id": "scouting_type",
      "display_name": "Scouting Type",
      "type": "string"
    }
  ],
  "auto": [
    {
      "id": "stopped",
      "display_name": "Stopped",
      "type": "boolean"
    },
    {
      "id": "collected_algae",
      "display_name": "Collected Algae",
      "type": "integer"
    },
    {
      "id": "reef_removed_algae",
      "display_name": "Removed Algae",
      "type": "integer"
    },
    {
      "id": "processed_algae",
      "display_name": "Processed Algae",
      "type": "integer"
    },
    {
      "id": "collected_coral",
      "display_name": "Collected Coral",
      "type": "integer"
    },
    {
      "id": "reef_level_1_placed",
      "display_name": "L1 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_1_missed",
      "display_name": "L1 Missed",
      "type": "integer"
    },
    {
      "id": "reef_level_2_placed",
      "display_name": "L2 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_2_missed",
      "display_name": "L2 Missed",
      "type": "integer"
    },
    {
      "id": "reef_level_3_placed",
      "display_name": "L3 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_3_missed",
      "display_name": "L3 Missed",
      "type": "integer"
    },
    {
      "id": "reef_level_4_placed",
      "display_name": "L4 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_4_missed",
      "display_name": "L4 Missed",
      "type": "integer"
    },
    {
      "id": "net_scored",
      "display_name": "Net Scored",
      "type": "integer"
    },
    {
      "id": "net_missed",
      "display_name": "Net Missed",
      "type": "integer"
    }
  ],
  "tele": [
    {
      "id": "lost_comms",
      "display_name": "Lost Comms",
      "type": "boolean"
    },
    {
      "id": "played_defense",
      "display_name": "Played Defense",
      "type": "boolean"
    },
    {
      "id": "reef_removed_algae",
      "display_name": "Removed Algae",
      "type": "integer"
    },
    {
      "id": "processed_algae",
      "display_name": "Processed Algae",
      "type": "integer"
    },
    {
      "id": "collected_coral",
      "display_name": "Collected Coral",
      "type": "integer"
    },
    {
      "id": "reef_level_1_placed",
      "display_name": "L1 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_1_missed",
      "display_name": "L1 Missed",
      "type": "integer"
    },
    {
      "id": "reef_level_2_placed",
      "display_name": "L2 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_2_missed",
      "display_name": "L2 Missed",
      "type": "integer"
    },
    {
      "id": "reef_level_3_placed",
      "display_name": "L3 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_3_missed",
      "display_name": "L3 Missed",
      "type": "integer"
    },
    {
      "id": "reef_level_4_placed",
      "display_name": "L4 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_4_missed",
      "display_name": "L4 Missed",
      "type": "integer"
    },
    {
      "id": "net_scored",
      "display_name": "Net Scored",
      "type": "integer"
    },
    {
      "id": "net_missed",
      "display_name": "Net Missed",
      "type": "integer"
    }
  ],
  "endgame": [
    {
      "id": "cage",
      "display_name": "Cage",
      "type": "string",
      "enum": [
        "park",
        "shallow",
        "deep"
      ]
    }
  ]
}
